# Generated by Django 4.2 on 2024-12-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='state',
        ),
    ]
