# Generated by Django 4.2 on 2024-12-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_usersignup_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynotes',
            name='mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
